on:
  release:
    types: [published]
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: npm
          registry-url: https://registry.npmjs.org
      - run: npx @nlib/cleanup-package-json --file package.json
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
